### PR TITLE
Update middleware to match new Vapor code

### PR DESCRIPTION
**Pull request by ketzusaka**

### CODE REVIEW

**Comment by ketzusaka** [comment]
@tannernelson This is breaking due to the tag not being updated. Not sure what our process is on that but wanted to let you know that.

**Comment by tanner0101** [comment]
I'll tag the latest, then re run.

**Comment by tanner0101** [comment]
It doesn't look like re-running the tests is notifying GitHub... Can you push another commit to trigger them?

**Comment by tanner0101** [comment]
`request.session["name"] = "Vapor"`

we need to make sessions optional as well.

**Pull request merged**
