### PR TITLE
Fix unthrown for View() in main.swift:5

### PR DESCRIPTION
**Pull request by DK1DA**
```
/app/Sources/main.swift:5:10: error: call can throw but is not marked with 'try'
                return View(path: "welcome.html")
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
```

### CODE REVIEW

**Comment by DK1DA** [comment]
Ping @tannernelson getting many exception because people are trying to click on the link to deploy on swifton.me but the app won't compile.

**Comment by tanner0101** [comment]
@kimar Thanks for the fix!

**Comment by tanner0101** [comment]
I'm looking into getting CI testing setup here so this doesn't happen again.

**Comment by tanner0101** [comment]
Hey @kimar it looks like the Vapor Example is no longer building for Swifton. Any ideas what could be causing this?

**Comment by DK1DA** [comment]
@tannernelson there's lots of errors being thrown, see: https://serve.swifton.me/1d6765b5aa0947018a1f52178654af700644e8292b65692b7e98fe62173a7f14/logs

**Comment by DK1DA** [comment]
Seems to be coming from `Mustache`... it's a bit messy right now as most frameworks already target Swift 3.0 but it's super flakey

**Comment by tanner0101** [comment]
What Swift version is it trying to build with?

**Comment by DK1DA** [comment]
`Swift version 3.0-dev (LLVM b361b0fc05, Clang 11493b0f62, Swift 24a0c3de75)`

**Comment by tanner0101** [comment]
Which snapshot date is that?

**Comment by DK1DA** [comment]
Supposedly first of march 2016

**Comment by tanner0101** [comment]
Ah okay. Vapor only supports the latest snapshot ( impossible to support more than one ) 3-24. If you install swiftenv it will auto detect based on the .swift-version file.

**Comment by DK1DA** [comment]
@tannernelson `serve.swifton.me` now features `swiftenv` and will download and use the swift version defined in `.swift-version` if available. What I've noticed now is that builds take significantly longer, also when trying to deploy the Vapor example, the built process was stuck when compiling the JSON package without any useful log output. Seems the build process was either still compiling (for more than 20 minutes) or it was deadlocked for some reason...

**Pull request merged**
