### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by mpclarkson**
Great work on Vapor. I'm keeping a keen eye on it. I seem to have problems running `swift build` on OSX so I put together this Dockerfile to run the demo.

### CODE REVIEW

**Comment by tanner0101** [comment]
What was the build error? It's building fine for me on OS X 10.11.3 and `Apple Swift version 3.0-dev (LLVM f95d47afa7, Clang f66c5bb67b, Swift b745691a38)`

**Comment by tanner0101** [comment]
PR looks great. Thank you.

**Comment by mpclarkson** [comment]
When I  run `swift build` on 10.11.2 and `Apple Swift version 3.0-dev (LLVM a7663bb722, Clang 4ca3c7fa28, Swift 1c2f40e246)` I get an `Undefined symbols for architecture x86_64:` error. Full details are in this [gist](https://gist.github.com/mpclarkson/607f9a85c402d9c3a682). It's not unique to Vapour - I see it a lot so it's probably something to do with my environment.

**Comment by mpclarkson** [comment]
BTW - do you have a roadmap for Vapor? I'm keen to contribute but would prefer to focus on planned features rather than random stuff.

**Comment by tanner0101** [comment]
Ah yeah, that seems like an issue with the compiler. Have you tried `rm -rf .build`? That's fixed a similar looking error for me. 

And as for the roadmap, I'm working on putting together more comprehensive documentation (most likely in the form of a GitHub wiki). A roadmap will be included there for sure.

**Comment by mpclarkson** [comment]
I'm pretty sure it's related to this bug: https://bugs.swift.org/browse/SR-235

**Pull request merged**
